[package]
name = "memory_checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = {version = "0.29.10", default-features = false}
# notify-rust = "*"
mac-notification-sys = "0.6"
